service: cors-proxy

provider:
  profile: cheddarup
  name: aws
  runtime: nodejs8.10
  timeout: 30
  stage: dev
  region: us-east-1
  apiGateway:
    binaryMediaTypes:
      - '*/*'

functions:
  lambda:
    name: cors-proxy
    handler: handler.corsProxy
    events:
      - http:
          path: ''
          method: get
          cors: true
      - http:
          path: ''
          method: post
          cors: true
