service: cors-proxy

provider:
  name: aws
  runtime: nodejs8.10
  timeout: 60
  stage: dev
  region: us-east-1

functions:
  lambda:
    name: cors-proxy
    handler: handler.corsProxy
    events:
      - http:
          path: ''
          method: get
          cors: true
      - http:
          path: ''
          method: post
          cors: true
